github_actions:
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('DBT_PROFILE_ACCOUNT') }}"
      user: "{{ env_var('DBT_PROFILE_USER') }}"
      role: dbt_prod_role
      password: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      database: dbt_hol_prod
      warehouse: dbt_prod_wh
      schema: public
dbt_core_snowflake:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: dbt_dev_role
      database: dbt_hol_dev
      warehouse: dbt_dev_wh
      schema: public
      threads: 200
  target: dev