version: 2

sources:
  - name: brazil_ecomm
    description: Brazilian E-Commerce Public Dataset by Olist
    database: raw
    schema: brazil_ecomm
    tables:
      - name: OLIST_CUSTOMERS_DATASET
      - name: OLIST_ORDER_ITEMS_DATASET
      - name: OLIST_ORDER_PAYMENTS_DATASET
      - name: OLIST_ORDERS_DATASET
      - name: OLIST_PRODUCTS_DATASET
      - name: PRODUCT_CATEGORY_NAME_TRANSLATION
      - name: OLIST_SELLERS_DATASET